### PR TITLE
KOGITO-5145: [DMN Designer] Data Types - Wizard - Create a Wizard component with 3 blank steps

### PR DESCRIPTION
**Pull request by yesamer**
Showcase available here: https://yesamer.github.io/import-java-classes/

### CODE REVIEW

**Review by jomarko — APPROVED** [review]
No comments from my site. Please wait for Dominik's review too.

**Review by domhanak — APPROVED** [review]

**Review by karreiro — COMMENTED** [review]
Thank you, @yesamer! Great stuff :-)

May we add some tests for the new components? We may use [this \_\_tests__ directory](https://github.com/karreiro/kogito-editors-java/tree/new-boxed-expression-master/kie-wb-common-react/boxed-expression-editor/src/__tests__) as a reference for that.

**Comment by yesamer** [comment]
@karreiro @vpellegrino  WDYT? Can you please check the PR? THx!

------------------------------|---------|----------|---------|---------|-------------------
File                          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------------------|---------|----------|---------|---------|-------------------
All files                     |     100 |      100 |     100 |     100 |                   
 components                   |     100 |      100 |     100 |     100 |                   
  index.ts                    |     100 |      100 |     100 |     100 |                   
 components/ImportJavaClasses |     100 |      100 |     100 |     100 |                   
  ImportJavaClasses.tsx       |     100 |      100 |     100 |     100 |                   
  ImportJavaClassesWizard.tsx |     100 |      100 |     100 |     100 |                   
  index.ts                    |     100 |      100 |     100 |     100 |                   
 components/ModalWizard       |     100 |      100 |     100 |     100 |                   
  ModalWizard.tsx             |     100 |      100 |     100 |     100 |                   
  index.ts                    |     100 |      100 |     100 |     100 |                   
 i18n                         |     100 |      100 |     100 |     100 |                   
  index.ts                    |     100 |      100 |     100 |     100 |                   
  setup.ts                    |     100 |      100 |     100 |     100 |                   
 i18n/locales                 |     100 |      100 |     100 |     100 |                   
  en.ts                       |     100 |      100 |     100 |     100 |                   
  index.ts                    |     100 |      100 |     100 |     100 |                   
------------------------------|---------|----------|---------|---------|-------------------

Test Suites: 2 passed, 2 total
Tests:       7 passed, 7 total
Snapshots:   7 passed, 7 total

**Review by vpellegrino — APPROVED** [review]
LGTM, thanks @yesamer

**Review by karreiro — APPROVED** [review]
Thank you, @yesamer 🚀

**Pull request merged**
