### PR TITLE
KOGITO-5147: Data Types - Wizard - Create the first step of the Wizard

### PR DESCRIPTION
**Pull request by yesamer**
JIRA: https://issues.redhat.com/browse/KOGITO-5147

Showcase: https://yesamer.github.io/import-java-classes/

### CODE REVIEW

**Comment by yesamer** [comment]
@karreiro Can you please perform a pre-review of this meanwhile I manage the tests? Thx!

**Review by karreiro — APPROVED** [review]
Great stuff, @yesamer!

**Comment by yesamer** [comment]
-------------------------------------------------|---------|----------|---------|---------|-------------------
File                                             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------------------------------------|---------|----------|---------|---------|-------------------
All files                                        |     100 |      100 |     100 |     100 |                   
 components                                      |     100 |      100 |     100 |     100 |                   
  index.ts                                       |     100 |      100 |     100 |     100 |                   
 components/EmptyStateWidget                     |     100 |      100 |     100 |     100 |                   
  EmptyStateWidget.tsx                           |     100 |      100 |     100 |     100 |                   
  index.ts                                       |     100 |      100 |     100 |     100 |                   
 components/ImportJavaClasses                    |     100 |      100 |     100 |     100 |                   
  ImportJavaClasses.tsx                          |     100 |      100 |     100 |     100 |                   
  ImportJavaClassesWizard.tsx                    |     100 |      100 |     100 |     100 |                   
  ImportJavaClassesWizardClassListTable.tsx      |     100 |      100 |     100 |     100 |                   
  ImportJavaClassesWizardClassListTableItems.tsx |     100 |      100 |     100 |     100 |                   
  ImportJavaClassesWizardFirstStep.tsx           |     100 |      100 |     100 |     100 |                   
  index.ts                                       |     100 |      100 |     100 |     100 |                   
 components/ModalWizard                          |     100 |      100 |     100 |     100 |                   
  ModalWizard.tsx                                |     100 |      100 |     100 |     100 |                   
  index.ts                                       |     100 |      100 |     100 |     100 |                   
 i18n                                            |     100 |      100 |     100 |     100 |                   
  index.ts                                       |     100 |      100 |     100 |     100 |                   
  setup.ts                                       |     100 |      100 |     100 |     100 |                   
 i18n/locales                                    |     100 |      100 |     100 |     100 |                   
  en.ts                                          |     100 |      100 |     100 |     100 |                   
  index.ts                                       |     100 |      100 |     100 |     100 |                   
-------------------------------------------------|---------|----------|---------|---------|-------------------

**Review by domhanak — APPROVED** [review]

**Review by vpellegrino — APPROVED** [review]
Fine from my side
Thanks @yesamer

**Pull request merged**
