### PR TITLE
KOGITO-5213: [DMN Designer] New boxed expression editor - Upgrade infrastructure following KOGITO-3560

### PR DESCRIPTION
**Pull request by karreiro**
[KOGITO-5213](https://issues.redhat.com/browse/KOGITO-5213): New boxed expression editor - Upgrade infrastructure following KOGITO-3560

Live demo: http://karreiro.com/kogito-editors-java

### CODE REVIEW

**Comment by karreiro** [comment]
Hey @vpellegrino :-)

I'm opening as a draft PR because I have one last thing to fix - the `build` script at the showcase web app. Everything else seems solid, stable, and ready for the review of your attentive eyes!

(I recommend a review by following each commit. The first one is the largest-one, because it moves all the files. However, the rest is quite simple) :-)

As soon as I fix the `build` script, I will convert this as a regular PR.

**Comment by karreiro** [comment]
Hi, @vpellegrino @jomarko I've fixed the last detail (showcase scripts). Now, the PR is fully ready for reviews :-)

**Comment by karreiro** [comment]
@vpellegrino changes applied (following your suggestions on GChat) 🚀  Thanks for the feedback :-)

**Review by vpellegrino — APPROVED** [review]
Thank you @karreiro

**Comment by karreiro** [comment]
(rebasing the branch..) 👀

**Comment by karreiro** [comment]
@yesamer I've moved the `import-java-classes` component to the `kogito-editors-js` with the upgraded React. I've slightly changed some config files and the name to `import-java-classes-component` following the `kogito-editors-js` conventions. I've tested it, the web app is running fine, and the quality checks are passing as well.

Also, for now, I'm keeping the `hello-world-component` as a reference. As soon as we have other component in the DMN loader, I believe we can to remove it :-)

**Comment by yesamer** [comment]
@karreiro Thank you!  Just a question, why some files are not marked as  renamed (eg. ModalWizard.test.tsx) ?

**Comment by karreiro** [comment]
@yesamer After I moved, I ran "yarn format" in the root (applying the standard format across all files, otherwise the build of `Kogito-editors-js` breaks).

Maybe Git is marking as "removed"/"added" because the file had its format considerably changed.

**Comment by yesamer** [comment]
@karreiro Right, I didn't apply any format check on tests, shame on me! :)

**Review by yesamer — APPROVED** [review]
LGTM!

**Review by jomarko — APPROVED** [review]
I will do a proper review once we open PR for main.

Just FYI, it seems to me we have some styling issue for Section Divider Titles. Shouldn't be the left and top margin for "OUTPUT CLAUSE" few more pixels?
Screenshot from 2021-07-21 07-23-16

**Pull request merged**
